### ISSUE TITLE
Can't use typecheck with "@vuedx/typecheck": "^0.4.1 and "postcss": "^8.2.2"

### ISSUE THREAD

**Issue by suienzan** [znck/vue-developer-experience#134]
**Describe the bug**

Can't use typecheck with "@vuedx/typecheck": "^0.4.1 and "postcss": "^8.2.2"

**To Reproduce**

```shell
yarn create vite-app test --template vue-ts
cd test
yarn install
yarn add -D postcss
echo "module.exports = { plugins: {} };" > postcss.config.js
yarn add -D @vuedx/typecheck
yarn vuedx-typecheck .
```

It returns `Error: Cannot send messages to a closed server connection.`

If I don't upgrade `@vuedx/typecheck` with `yarn add -D @vuedx/typecheck`, it works as expected.

**Expected behavior**

show typecheck result with lastest version of `@vuedx/typecheck`.

**Screenshots/Recording**

**Info (please complete the following information):**

- OS: Arch Linux
- TypeScript Version: 4.1.3
- Vue Version: 3.0.5

**Comment by anbraten** [comment]
After upgrading from `0.2.4-0` to `0.4.2-insiders-1610169628.0` I got a similar error:

```bash
$ vuedx-typecheck
Running for /home/anton/Projects/project-leek/packages/app
(node:230626) UnhandledPromiseRejectionWarning: Error: Cannot send messages to a closed server connection.
    at TypeScriptServerHost.send (/home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:373:19)
    at TypeScriptServerHost.sendRequest (/home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:392:25)
    at TypeScriptServerHost.sendCommand (/home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:420:21)
    at refresh (/home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:481:31)
    at /home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:544:20
    at /home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:369:106
    at Array.forEach (<anonymous>)
    at TypeScriptServerHost.onEvent (/home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:369:90)
    at Interface.<anonymous> (/home/anton/Projects/project-leek/node_modules/@vuedx/typecheck/dist/index.cjs.js:356:26)
    at Interface.emit (events.js:315:20)
(node:230626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:230626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

<--- Last few GCs --->

[230626:0x3dd4460]    20449 ms: Mark-sweep 2047.2 (2052.9) -> 2047.2 (2052.9) MB, 28.5 / 0.1 ms  (average mu = 0.229, current mu = 0.001) last resort GC in old space requested
[230626:0x3dd4460]    20475 ms: Mark-sweep 2047.2 (2052.9) -> 2047.2 (2052.9) MB, 25.3 / 0.1 ms  (average mu = 0.136, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0e6f69c008d1 <JSObject>
    0: builtin exit frame: utf8Slice(this=0x2cc78454dc99 <Uint8Array map = 0x1199d0254b9>,1370202,0,0x2cc78454dc99 <Uint8Array map = 0x1199d0254b9>)

    1: slice [0x1c325239709] [buffer.js:607] [bytecode=0x4b8772c1a71 offset=7](this=0x01c325238ce9 <Object map = 0x1199d025fa9>,0x2cc78454dc99 <Uint8Array map = 0x1199d0254b9>,0,1370202)
    2: toString [0x93231e084d9] [buffer.js:804] [bytecode=0x4...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0xa0bb60 node::Abort() [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 2: 0xa0bf6c node::OnFatalError(char const*, char const*) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 3: 0xb820fe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 4: 0xb82479 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 5: 0xd2ee35  [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 6: 0xd3f748 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 7: 0xd0d59c v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 8: 0xd0dd5d v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const> const&, v8::internal::AllocationType) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
 9: 0xb9a45f v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
10: 0xae1450 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
11: 0x9e5fe6  [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
12: 0xbee089  [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
13: 0xbefe77 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
14: 0x13ccf79  [/home/anton/.nvm/versions/node/v12.18.2/bin/node]
Aborted (core dumped)
```
